name: Sync Main Branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: yoshan0921/Favr
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: true

      - name: Check token length
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo -n $GH_TOKEN | wc -c

      - name: Remove workflow files
        run: rm -rf .github/workflows

      - name: Configure Git with token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "yoshan0921"
          git config --global user.email "yhana0921@gmail.com"
          git remote add target https://yoshan0921:${GH_TOKEN}@github.com/yoshan0921/yoshan0921.github.io.git
          git remote -v
          git branch
          git status

      - name: Verify the current directory
        run: ls -la

      - name: Push to target repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: git push target main --force
