name: Sync with Target Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: yoshan0921/Favr
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false

      - name: Create bare mirror clone
        run: |
          git clone --bare https://github.com/yoshan0921/Favr.git Favr.git
          cd Favr.git
          git remote add target https://yoshan0921:${{ secrets.GH_TOKEN }}@github.com/yoshan0921/yoshan0921.github.io.git

      - name: Verify remote settings
        run: |
          cd Favr.git
          git remote -v

      - name: Push to target repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd Favr.git
          git fetch origin main
          git push target +refs/heads/main:refs/heads/main --force
